query TransferInReceipt_Query(
  $transferInId: ID!
) {
  viewer {
    name
    cpf
    savingsAccount {
      id
      bankAccount {
        number
        checkDigit
        branch
        bank {
          name
        }
        id
      }
      transferInEvent(transferInId: $transferInId) {
        postDate
        amount
        sourceType
        originAccount {
          id
          branch
          number
          digit
          personIdentifier
          name
          bank {
            name
            number
          }
        }
        id
      }
    }
    id
  }
}
